[project]
name = "seagull"
authors = [{ name = "Justin Mayer", email = "authors@getpelican.com" }]
description = "An opinionated re-implementation of the Pelican static site generator"
version = "0.1.0-dev"
license = { text = "AGPLv3" }
readme = "README.rst"
keywords = ["static site generator", "static sites", "ssg"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Framework :: Pelican",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content :: Content Management System",
    "Topic :: Internet :: WWW/HTTP :: Site Management",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup :: Markdown",
    "Topic :: Text Processing :: Markup :: HTML",
    "Topic :: Text Processing :: Markup :: reStructuredText",
]
requires-python = ">=3.14"
dependencies = [
    "click-extra>=7.5.0",
    #    "blinker>=1.7.0",
    "docutils>=0.22.0",
    "python-slugify>=8.0",
    "BeautifulSoup4>=4.14",
    #    "feedgenerator>=2.1.0",
    "jinja2>=3.1.2",
    #    "ordered-set>=4.1.0",
    #    "pygments>=2.16.1,<2.20.0",
    #    "python-dateutil>=2.8.2",
    #    "rich>=13.6.0",
    #    "unidecode>=1.3.7",
    "watchfiles>=0.24.0",
    #    "tzdata; sys_platform == 'win32'",
]

[project.optional-dependencies]
markdown = ["markdown>=3.1"]

[project.urls]
Homepage = "https://getpelican.com"
Funding = "https://donate.getpelican.com/"
"Issue Tracker" = "https://github.com/getpelican/pelican/issues"
Repository = "https://github.com/getpelican/pelican"
Documentation = "https://docs.getpelican.com"

[project.scripts]
seagull = "seagull.cli:main"
#pelican-import = "pelican.tools.pelican_import:main"
#pelican-plugins = "pelican.plugins._utils:list_plugins"
#pelican-quickstart = "pelican.tools.pelican_quickstart:main"
#pelican-themes = "pelican.tools.pelican_themes:main"

[tool.autopub]
project-name = "Seagull"
git-username = "botpub"
git-email = "52496925+botpub@users.noreply.github.com"
changelog-file = "docs/changelog.rst"
changelog-header = "###############"
version-header = "="

[tool.pdm]
ignore_package_warnings = ["sphinx"]

[tool.pdm.scripts]
docbuild = "invoke docbuild"
docserve = "invoke docserve"
lint = "invoke lint"
test = "invoke tests"

[tool.pdm.dev-dependencies]
dev = [
    #    "BeautifulSoup4>=4.13.3",
    #    "jinja2>=3.1.2",
    #    "lxml>=4.9.3",
    #    "markdown>=3.5.1",
    #    "typogrify>=2.1.0",
    #    "sphinx>=7.1.2",
    #    "sphinxext-opengraph>=0.9.0",
    #    "furo==2025.9.25",
    #    "livereload>=2.6.3",
    #    "pre-commit>=4.5",
    #    "psutil>=5.9.6",
    #    "pygments>=2.16.1,<2.20.0",
    #    "pytest>=7.4.3",
    #    "pytest-cov>=4.1.0",
    #    "pytest-sugar>=0.9.7",
    #    "pytest-xdist>=3.4.0",
    #    "tox>=4.11.3",
    #    "invoke>=2.2.0",
    # ruff version should match the one in .pre-commit-config.yaml
    #    "ruff==0.14.14",
    #    "tomli>=2.0.1; python_version < \"3.11\"",
]

[tool.pdm.build]
source-includes = [
    "CONTRIBUTING.rst",
    "THANKS",
    "docs/changelog.rst",
    "samples/",
]
excludes = [
    #    "pelican/build/"
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]

extend-exclude = ["./pelican/", "./tasks.py", "./docs/", "./samples/"]

[tool.ruff.lint]

select = [
    "E",
    "W",
    "F",
    "N",
    # the rest in alphabetical order:
    "A",
    "ARG",
    "B",
    "BLE",
    # TODO: Do I want the full "COM"
    "COM818",
    "COM819",
    "C4",
    "DTZ",
    "EM103",
    "EXE",
    "ERA",
    "FURB",
    "FBT",
    # FIXME doesn't seem to work with our imported logger
    "G",
    "I", # isort
    "ICN",
    "INP",
    "INT",
    "ISC",
    "LOG",
    "PERF",
    "PIE",
    "PL", # pylint
    "PYI",
    "RET",
    "RSE",
    "RUF",
    "SIM",
    "SLF",
    "SLOT",
    "TID",
    "UP",
    "Q",
    "TCH",
    "T10",
    "T20",
    "S",
    "YTT",
    "ANN",
]

ignore = [
    # FIXME enable autoescape and disable for formatted fields
    # With our usage, we actually want autoescape to be False
    "S701"
]

[tool.ruff.lint.pycodestyle]

ignore-overlong-task-comments = true

[tool.ruff.lint.flake8-annotations]

mypy-init-return = true
